name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64_64, aarch64]
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
                libv4l-dev \
                libaa1-dev \
                libasound2-dev \
                libdv-dev \
                libfs-dev \
                libgl1-mesa-dev \
                libglib2.0-dev \
                libjpeg-dev \
                liblircclient-dev \
                libmotif-dev \
                libncurses5-dev \
                libpng-dev \
                libquicktime-dev \
                libx11-dev \
                libxaw7-dev \
                libxext-dev \
                libxft-dev \
                libxinerama-dev \
                libxmu-dev \
                libxpm-dev \
                libxrandr-dev \
                libxt-dev \
                libxv-dev \
                libxxf86dga-dev \
                libxxf86vm-dev \
                libzvbi-dev \
                po-debconf \
                x11-xserver-utils \
                x11proto-core-dev

      - name: build
        run: |
          autoreconf -vfi
          ./configure
          make
          sudo make install
